# Questão 5 da lista de IA

## a) Estime o vetor média e a matriz de covariância de cada distribuição gaussiana multivariada.

### Importação das bibliotecas

In [37]:
import numpy as np

### Declaração das distribuições e cálculo da média e da matriz de covariância

$\mu_{w1} = 
\begin{bmatrix}
\mu_{w1\_x1}\\ 
\mu_{w1\_x2}
\end{bmatrix}$

$\mu_{w2} = 
\begin{bmatrix}
\mu_{w2\_x1}\\ 
\mu_{w2\_x2}
\end{bmatrix}$

In [60]:
# Declarando os vetores
w1_x1 = [-5.01,-5.43,1.08,0.86,-2.67,4.94,-2.51,-2.25,5.56,1.03]
w1_x2 = [-8.12,-3.48,-5.52,-3.78,0.63,3.29,2.09,-2.13,2.86,-3.33]
w2_x1 = [-0.91,1.3,-7.75,-5.47,6.14,3.6,5.37,7.18,-7.39,-7.5]
w2_x2 = [-0.18,-2.06,-4.54,0.5,5.72,1.26,-4.63,1.46,1.17,-6.32]

In [61]:
# Calculando as médias
avg_w1_x1 = np.mean(w1_x1)
avg_w1_x2 = np.mean(w1_x2)
avg_w2_x1 = np.mean(w2_x1)
avg_w2_x2 = np.mean(w2_x2)

$\sigma_{w1} = \begin{bmatrix}
s_{w1\_11} & s_{w1\_12} \\
s_{w1\_21} & s_{w1\_22}
\end{bmatrix}$ 

$\sigma_{w2} = \begin{bmatrix}
s_{w2\_11} & s_{w2\_12} \\
s_{w2\_21} & s_{w2\_22}
\end{bmatrix}$ 

In [50]:
# Calculando as matrizes de covariância

w1_s11 = 0
w1_s12 = 0
w1_s21 = 0
w1_s22 = 0
for i in range(0,10):
  w1_s11 += (w1_x1[i]-avg_w1_x1)*(w1_x1[i]-avg_w1_x1)
  w1_s12 += (w1_x1[i]-avg_w1_x1)*(w1_x2[i]-avg_w1_x2)
  w1_s21 += (w1_x2[i]-avg_w1_x2)*(w1_x1[i]-avg_w1_x1)
  w1_s22 += (w1_x2[i]-avg_w1_x2)*(w1_x2[i]-avg_w1_x2)

w1_s11 = round(w1_s11/9, 4)
w1_s12 = round(w1_s12/9, 4)
w1_s21 = round(w1_s21/9, 4)
w1_s22 = round(w1_s22/9, 4)

matriz_w1 = [[w1_s11, w1_s12], [w1_s21, w1_s22]]
matriz_w1

[[14.3805, 7.6954], [7.6954, 14.6231]]

In [63]:
# Calculando as matrizes de covariância

w2_s11 = 0
w2_s12 = 0
w2_s21 = 0
w2_s22 = 0
for i in range(0,10):
  w2_s11 += (w2_x1[i]-avg_w2_x1)*(w2_x1[i]-avg_w2_x1)
  w2_s12 += (w2_x1[i]-avg_w2_x1)*(w2_x2[i]-avg_w2_x2)
  w2_s21 += (w2_x2[i]-avg_w2_x2)*(w2_x1[i]-avg_w2_x1)
  w2_s22 += (w2_x2[i]-avg_w2_x2)*(w2_x2[i]-avg_w2_x2)

w2_s11 = round(w2_s11/9, 4)
w2_s12 = round(w2_s12/9, 4)
w2_s21 = round(w2_s21/9, 4)
w2_s22 = round(w2_s22/9, 4)

matriz_w2 = [[w2_s11, w2_s12], [w2_s21, w2_s22]]
matriz_w2

[[36.8293, 9.9809], [9.9809, 13.1686]]

## b) Determine a superfície de decisão

In [64]:
avg_w1 = np.asarray([
    [avg_w1_x1],
    [avg_w1_x2]
], dtype='float32')

avg_w2 = np.asarray([
    [avg_w2_x1],
    [avg_w2_x2]
], dtype='float32')

cov_w1 = np.asarray([
    [w1_s11, w1_s12],
    [w1_s21, w1_s22]
], dtype='float32')

cov_w2 = np.asarray([
    [w2_s11, w2_s12],
    [w2_s21, w2_s22]
], dtype='float32')

print(avg_w1)
print(avg_w2)
print(cov_w1)
print(cov_w2)

[[-0.44 ]
 [-1.749]]
[[-0.543]
 [-0.762]]
[[14.3805  7.6954]
 [ 7.6954 14.6231]]
[[36.8293  9.9809]
 [ 9.9809 13.1686]]


In [65]:
# Função discriminante g1
def g1(x):
  t1 = np.transpose(x-avg_w1)
  t2 = np.linalg.inv(cov_w1)
  t3 = x-avg_w1
  t4 = np.dot(t1, t2)
  t5 = np.dot(t4, t3)
  t6 = np.log(np.linalg.det(cov_w1))
  r = float(-0.5*t5 - 0.5*t6)
  return round(r,4)

In [66]:
# Função discriminante g2
def g2(x):
  t1 = np.transpose(x-avg_w2)
  t2 = np.linalg.inv(cov_w2)
  t3 = x-avg_w2
  t4 = np.dot(t1, t2)
  t5 = np.dot(t4, t3)
  t6 = np.log(np.linalg.det(cov_w2))
  r = float(-0.5*t5 - 0.5*t6)
  return round(r,4)

## c) Classifique os pontos (padrões) (1, 2)t , (5, 3)t , (0, 0)t , (1, 0)t , decidindo pela classe com maior valor das funções discriminantes, isto e, max{gi(x)} ou faça pela região definida pela superfície de separação (função descriminante)

In [67]:
#Ponto (1,2)
ponto1 = np.asarray([
    [1,2]
], dtype='float32')
ponto1 = np.transpose(ponto1)
print(g1(ponto1))
print(g2(ponto1))

-3.0032
-3.2719


In [68]:
#Ponto (5,3)
ponto2 = np.asarray([
    [5,3]
], dtype='float32')
ponto2 = np.transpose(ponto2)
print(g1(ponto2))
print(g2(ponto2))

-3.6986
-3.6383


In [69]:
#Ponto (0,0)
ponto3 = np.asarray([
    [0,0]
], dtype='float32')
ponto3 = np.transpose(ponto3)
print(g1(ponto3))
print(g2(ponto3))

-2.6246
-2.9992


In [70]:
#Ponto (1,0)
ponto4 = np.asarray([
    [1,0]
], dtype='float32')
ponto4 = np.transpose(ponto4)
print(g1(ponto4))
print(g2(ponto4))

-2.6265
-3.0151
